GraphQLHttpMiddleware returns 400 when query is missing
graphql-dotnet/server pull request #584
Opened 2021-05-25 15:36 UTC by sharppanda

Fixes #583

2021-05-25 15:51 UTC, Shane32 requested changes

2021-05-25 15:51 UTC, Shane32 commented on src/Transports.AspNetCore/GraphQLHttpMiddleware.cs
> +                if (string.IsNullOrWhiteSpace(urlGQLRequest.Query))
```suggestion
                if (string.IsNullOrWhiteSpace(gqlRequest.Query))
```

2021-05-25 16:47 UTC, Shane32 approved these changes
Looks good to me but @sungam3r needs to approve it.

2021-05-31 13:56 UTC, sharppanda commented
Do you have an ETA when this could be reviewed by @sungam3r ?

2021-06-10 14:45 UTC, Shane32 commented
@sungam3r bump

2021-06-14 14:40 UTC, merged

2021-11-18 20:24 UTC, sungam3r commented
@sharppanda Thanks for fixing this. 

> Do you have an ETA when this could be reviewed by @sungam3r ?

I had a long break from OSS this year so...just reviewed! LGTM